version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ac-network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - ac-network
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  ac-web:
    image: gasperqt/wow-amnesia
    container_name: ${NAME_CONTAINER}
    restart: always
    expose:
      - "80"
    volumes:
      - ./sites/custom:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=servercustom.zapto.org
      - LETSENCRYPT_HOST=servercustom.zapto.org
      - LETSENCRYPT_EMAIL=cueva.renato@gmail.com
    networks:
      - ac-network
    depends_on:
      - nginx-proxy
      - letsencrypt
networks:
  ac-network:
    external:
      name: ac-network
volumes: 
  certs:
  html:
  vhostd: